import os
from pathlib import Path
import streamlit as st
import numpy as np
from PIL import Image
import tensorflow as tf
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras import layers, models
import plotly.graph_objects as go

# -----------------------------
# 1. Path Definition (Relative)
# -----------------------------
BASE_DIR = Path(__file__).resolve().parent
ICON_PATH = str(BASE_DIR / "gemini-svg.svg")
MODEL_PATH = str(BASE_DIR / "models" / "best_model.keras")

# -----------------------------
# 2. Page Configuration
# -----------------------------
st.set_page_config(
    page_title="NeuroScan AI - Brain Tumor Detection",
    page_icon=ICON_PATH if os.path.exists(ICON_PATH) else "🧠",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for styling
st.markdown("""
    <style>
    .block-container { padding-top: 2rem; padding-bottom: 2rem; }
    div[data-testid="stMetricValue"] { font-size: 1.8rem; }
    </style>
""", unsafe_allow_html=True)

# -----------------------------
# 3. Sidebar Setup
# -----------------------------
with st.sidebar:
    if os.path.exists(ICON_PATH):
        st.image(ICON_PATH, width=80)
    
    st.title("NeuroScan AI")
    st.caption("Brain Tumor Diagnostic Platform")
    
    st.markdown("---")
    
    uploaded_file = st.file_uploader(
        "Upload Brain MRI Scan",
        type=["jpg", "jpeg", "png"]
    )
    
    st.markdown("---")
    st.markdown("### 📋 System Info")
    st.caption("• **Model:** EfficientNet Deep Learning")
    st.caption("• **Target Classes:** Glioma, Meningioma, Pituitary, No Tumor")

# -----------------------------
# 4. Model Loading via Weights
# -----------------------------
@st.cache_resource
def load_my_model():
    # 1. First attempt direct loading
    try:
        return tf.keras.models.load_model(MODEL_PATH, compile=False)
    except Exception:
        pass

    # 2. Robust Fallback: Build EfficientNetB0 architecture and load weights
    base_model = EfficientNetB0(weights=None, include_top=False, input_shape=(224, 224, 3))
    x = layers.GlobalAveragePooling2D()(base_model.output)
    x = layers.Dropout(0.2)(x)
    outputs = layers.Dense(4, activation="softmax")(x)
    
    model = models.Model(inputs=base_model.input, outputs=outputs)
    
    # Load weights directly from the .keras artifact
    model.load_weights(MODEL_PATH)
    return model

model = load_my_model()

class_names = [
    "Glioma",
    "Meningioma",
    "No Tumor",
    "Pituitary"
]

# -----------------------------
# 5. Main Interface
# -----------------------------
st.title("Brain Tumor Detection Dashboard")
st.write("Upload an MRI scan in the sidebar to view deep learning classification results.")

st.markdown("---")

if uploaded_file is not None:
    # Preprocess image
    image = Image.open(uploaded_file).convert("RGB")
    img = image.resize((224, 224))
    img_array = tf.keras.utils.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = tf.keras.applications.efficientnet.preprocess_input(img_array)

    # Prediction
    prediction = model.predict(img_array, verbose=0)[0]
    predicted_index = np.argmax(prediction)
    predicted_class = class_names[predicted_index]
    confidence = prediction[predicted_index] * 100

    # -----------------------------
    # 2-Column Dashboard Layout
    # -----------------------------
    col1, col2 = st.columns([1, 1.2], gap="large")

    # Left Column: Image Preview
    with col1:
        st.subheader("🖼️ Uploaded MRI Scan")
        st.image(image, use_container_width=True)

    # Right Column: Diagnostic Results
    with col2:
        st.subheader("📊 Diagnostic Output")
        
        # Top Prediction Card
        st.success(f"**Predicted Diagnosis:** {predicted_class}")
        st.metric(
            label="Confidence Score",
            value=f"{confidence:.2f}%"
        )

        st.markdown("#### Class Probabilities")
        
        # Horizontal Plotly Bar Chart
        colors = ['#636EFA' if cls != predicted_class else '#00CC96' for cls in class_names]
        
        fig = go.Figure(
            go.Bar(
                x=prediction * 100,
                y=class_names,
                orientation="h",
                text=[f"{p*100:.1f}%" for p in prediction],
                textposition="auto",
                marker_color=colors
            )
        )

        fig.update_layout(
            xaxis_title="Probability (%)",
            yaxis_title="Class",
            height=280,
            margin=dict(l=10, r=10, t=10, b=10),
            xaxis=dict(range=[0, 100])
        )

        st.plotly_chart(fig, use_container_width=True)

        # Numerical breakdown
        with st.expander("Detailed Probability Breakdown", expanded=False):
            for cls, prob in zip(class_names, prediction):
                st.write(f"**{cls}:** {prob*100:.2f}%")

    st.markdown("---")
    st.info(
        "⚠️ **Disclaimer:** This prediction is generated by an AI model and "
        "is intended for educational purposes only. "
        "It should not replace professional medical diagnosis."
    )

else:
    st.info("👈 Please select and upload an MRI scan from the sidebar to begin analysis.")