import os
from pathlib import Path
import streamlit as st
import numpy as np
from PIL import Image
import onnxruntime as ort
import plotly.graph_objects as go

# -----------------------------
# 1. Path Definition (Relative)
# -----------------------------
BASE_DIR = Path(__file__).resolve().parent
ICON_PATH = str(BASE_DIR / "gemini-svg.svg")
MODEL_PATH = str(BASE_DIR / "models" / "best_model.onnx")

# -----------------------------
# 2. Page Configuration
# -----------------------------
st.set_page_config(
    page_title="NeuroScan AI - Brain Tumor Detection",
    page_icon=ICON_PATH if os.path.exists(ICON_PATH) else "🧠",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for styling
st.markdown("""
    <style>
    .block-container { padding-top: 2rem; padding-bottom: 2rem; }
    div[data-testid="stMetricValue"] { font-size: 1.8rem; }
    </style>
""", unsafe_allow_html=True)

# -----------------------------
# 3. Sidebar Setup
# -----------------------------
with st.sidebar:
    if os.path.exists(ICON_PATH):
        st.image(ICON_PATH, width=80)
    
    st.title("NeuroScan AI")
    st.caption("Brain Tumor Diagnostic Platform")
    
    st.markdown("---")
    
    uploaded_file = st.file_uploader(
        "Upload Brain MRI Scan",
        type=["jpg", "jpeg", "png"]
    )
    
    st.markdown("---")
    st.markdown("### 📋 System Info")
    st.caption("• **Engine:** ONNX Runtime Engine")
    st.caption("• **Target Classes:** Glioma, Meningioma, Pituitary, No Tumor")

# -----------------------------
# 4. Model Loading (ONNX)
# -----------------------------
@st.cache_resource
def load_my_model():
    session = ort.InferenceSession(MODEL_PATH, providers=['CPUExecutionProvider'])
    return session

session = load_my_model()
input_name = session.get_inputs()[0].name
output_name = session.get_outputs()[0].name

class_names = [
    "Glioma",
    "Meningioma",
    "No Tumor",
    "Pituitary"
]

def preprocess_mri(img_pil):
    img = img_pil.resize((224, 224))
    img_arr = np.array(img, dtype=np.float32)
    img_arr = np.expand_dims(img_arr, axis=0)
    return img_arr

def softmax(x):
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / e_x.sum(axis=-1, keepdims=True)

# -----------------------------
# 5. Main Interface
# -----------------------------
st.title("Brain Tumor Detection Dashboard")
st.write("Upload an MRI scan in the sidebar to view deep learning classification results.")

st.markdown("---")

if uploaded_file is not None:
    # Preprocess image
    image = Image.open(uploaded_file).convert("RGB")
    input_data = preprocess_mri(image)

    # ONNX Inference
    raw_output = session.run([output_name], {input_name: input_data})[0][0]
    
    # Softmax normalization check
    prediction = softmax(raw_output) if (np.max(raw_output) > 1.0 or np.min(raw_output) < 0.0) else raw_output
    
    predicted_index = int(np.argmax(prediction))
    predicted_class = class_names[predicted_index]
    confidence = float(prediction[predicted_index] * 100)

    # -----------------------------
    # 2-Column Dashboard Layout
    # -----------------------------
    col1, col2 = st.columns([1, 1.2], gap="large")

    # Left Column: Image Preview
    with col1:
        st.subheader("🖼️ Uploaded MRI Scan")
        st.image(image, use_container_width=True)

    # Right Column: Diagnostic Results
    with col2:
        st.subheader("📊 Diagnostic Output")
        
        # Top Prediction Card
        st.success(f"**Predicted Diagnosis:** {predicted_class}")
        st.metric(
            label="Confidence Score",
            value=f"{confidence:.2f}%"
        )

        st.markdown("#### Class Probabilities")
        
        # Horizontal Plotly Bar Chart
        colors = ['#636EFA' if cls != predicted_class else '#00CC96' for cls in class_names]
        
        fig = go.Figure(
            go.Bar(
                x=prediction * 100,
                y=class_names,
                orientation="h",
                text=[f"{p*100:.1f}%" for p in prediction],
                textposition="auto",
                marker_color=colors
            )
        )

        fig.update_layout(
            xaxis_title="Probability (%)",
            yaxis_title="Class",
            height=280,
            margin=dict(l=10, r=10, t=10, b=10),
            xaxis=dict(range=[0, 100])
        )

        st.plotly_chart(fig, use_container_width=True)

        # Numerical breakdown
        with st.expander("Detailed Probability Breakdown", expanded=False):
            for cls, prob in zip(class_names, prediction):
                st.write(f"**{cls}:** {prob*100:.2f}%")

    st.markdown("---")
    st.info(
        "⚠️ **Disclaimer:** This prediction is generated by an AI model and "
        "is intended for educational purposes only. "
        "It should not replace professional medical diagnosis."
    )

else:
    st.info("👈 Please select and upload an MRI scan from the sidebar to begin analysis.")